"""
unified_server.py — one FastAPI service for the merged pipeline.

Two ways to use it:

  POST /ask
      { "question": "..." }
      Runs the FULL pipeline: Qwen generates an answer, the probe scores
      it (prob_hallucinated), and — if that score is at/above the
      Blackboard's risk threshold — the Blackboard agents verify the
      flagged claim against the knowledge base and correct/hedge the
      response. This is the new, merged entry point.

  POST /analyze
      { "prompt": "...", "response": "...", "confidence_score": 0.85 }
      The original Blackboard-arch endpoint, unchanged: bring your own
      risk score (e.g. from a different upstream detector) and just run
      the mitigation stage. Kept for backward compatibility / standalone
      testing of the Blackboard half without loading the Qwen model.

Startup requires:
  - GROQ_API_KEY set (Blackboard's Verifier/Correction/ClaimExtractor agents)
  - PROBE_PATH pointing at a trained probe .joblib (see probe/train_probe.py)
  - a CUDA GPU (the probe's feature extractor refuses to run on CPU)

Run:
  export GROQ_API_KEY=your_key_here
  export PROBE_PATH=/path/to/probe.joblib
  uvicorn unified_server:app --host 0.0.0.0 --port 8000
"""

import os
import sys
from pathlib import Path
from typing import Any, Dict, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

_ROOT = Path(__file__).resolve().parent
for _sub in ("probe", "blackboard"):
    _p = str(_ROOT / _sub)
    if _p not in sys.path:
        sys.path.insert(0, _p)

import blackboard_core as bc  # blackboard/blackboard_core.py — /analyze uses this directly
from pipeline import HallucinationMitigationPipeline

app = FastAPI(title="Merged Hallucination Detection + Mitigation Pipeline")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

PROBE_PATH = os.environ.get("PROBE_PATH")
PROBE_LAYER = int(os.getenv("PROBE_LAYER", "20"))
MODEL_ID = os.getenv("QWEN_MODEL_ID", "Qwen/Qwen2.5-7B-Instruct")

# Loaded lazily on first /ask call (not at import time) so /analyze and
# /health work even without a GPU / probe available, e.g. in CI.
_pipeline: Optional[HallucinationMitigationPipeline] = None


def get_pipeline() -> HallucinationMitigationPipeline:
    global _pipeline
    if _pipeline is None:
        if not PROBE_PATH:
            raise HTTPException(
                status_code=503,
                detail="PROBE_PATH is not set — point it at a trained probe .joblib "
                       "(see probe/train_probe.py) before calling /ask.",
            )
        _pipeline = HallucinationMitigationPipeline(
            probe_path=PROBE_PATH, layer=PROBE_LAYER, model_id=MODEL_ID,
        )
    return _pipeline


class AskRequest(BaseModel):
    question: str
    max_new_tokens: int = 32


class ScoreAndMitigateRequest(BaseModel):
    question: str
    answer: str


class AnalyzeRequest(BaseModel):
    prompt: str
    response: str
    confidence_score: float


@app.post("/ask")
def ask(req: AskRequest) -> Dict[str, Any]:
    """Full pipeline: generate -> score -> (maybe) verify & correct."""
    pipeline = get_pipeline()
    try:
        return pipeline.run(req.question, max_new_tokens=req.max_new_tokens)
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Pipeline error: {exc}")


@app.post("/score_and_mitigate")
def score_and_mitigate(req: ScoreAndMitigateRequest) -> Dict[str, Any]:
    """Same as /ask, but for an answer you already have (e.g. generated by
    a different model upstream) instead of one Qwen generates here."""
    pipeline = get_pipeline()
    try:
        return pipeline.run_on_qa(req.question, req.answer)
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Pipeline error: {exc}")


@app.post("/analyze")
def analyze(req: AnalyzeRequest) -> Dict[str, Any]:
    """Original Blackboard-arch endpoint — bring your own confidence_score."""
    try:
        return bc.process_response(
            prompt=req.prompt,
            response=req.response,
            confidence_score=req.confidence_score,
        )
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Pipeline error: {exc}")


@app.get("/health")
def health() -> Dict[str, Any]:
    return {
        "status": "ok",
        "knowledge_docs": bc.knowledge_collection.count(),
        "memory_docs": bc.memory_collection.count(),
        "threshold": bc.HALLUCINATION_RISK_THRESHOLD,
        "probe_loaded": _pipeline is not None,
        "probe_path": PROBE_PATH,
    }


# Reuses the existing Blackboard trace demo frontend. Must be mounted last.
app.mount("/", StaticFiles(directory=str(_ROOT / "blackboard" / "static"), html=True), name="static")
